CREATE TABLE IF NOT EXISTS invites (
    token TEXT NOT NULL UNIQUE PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    admin_id INTEGER NOT NULL REFERENCES users(id), 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
